#!/usr/bin/env python3
# (c) 2018 Alexander Sharihin 
# Small utility for converting black and white TIC80 gif sprites to zx-spectrum tiles.

import sys
from PIL import Image

def readSprite(img, x, y):
    result = []
    for offsetY in range(8):
        byte = 0
        for offsetX in range(8):
            pixel = img.getpixel((x+offsetX, y+offsetY)) == 15
            if (pixel):
                byte = byte | 1 << offsetX
        result.append(byte)
    return result

def readSprites(img, xCount, yCount):
    buffer = []
    for y in range(xCount):
        for x in range(yCount):
            buffer = buffer + readSprite(image, x * 8, y * 8)
    return buffer

if (len(sys.argv) < 4):
    print("Usage: ./sprites.py <sprites.gif> <x-count> <y-count> <out.bin>")
    sys.exit()
    
image = Image.open(sys.argv[1])
cx = 16
cy = int(sys.argv[2])

with open(sys.argv[3], "w") as fp:
    fp.write('//Do not edit this autogenerated code \nstatic char sprites[] = {\n\t')
    sprites = readSprites(image, cx, cy)
    counter = 0
    for data in sprites:
        fp.write(str(data))
        fp.write(', ')
        counter = counter + 1
        if (counter % (8*16) == 0): 
            fp.write('\n\t')
    fp.write('0\n};\n')
